.TH man 2 "2019-10-08" "hacker manifesto"
.SH NAME
hacker \- manifesto hacker
.SH SYNOPSIS
Apenas leia e medite sobre.
.SH DESCRIPTION
Inglês
Outro foi pego hoje, está em todos os jornais. "Adolescente preso em escândalo de crimes de informática", "Hacker preso após adulteração de banco" ... Maldição crianças. Eles são todos iguais.Mas você, em sua psicologia de três partes e no tecnobrain de 1950, já deu uma olhada por trás dos olhos do hacker? Você já se perguntou o que o fez funcionar, que forças o moldaram, o que pode tê-lo moldado? Eu sou um hacker, entre no meu mundo ...
O meu é um mundo que começa com a escola ... sou mais esperto do que a maioria das outras crianças, essa porcaria que eles nos ensinam me entedia ...

Maldito fracassado. Eles são todos iguais.

Eu estou no ensino fundamental ou médio. Eu escutei professores explicar pela décima quinta vez como reduzir uma fração. Eu entendo. "Não, Sra. Smith, eu não mostrei o meu trabalho. Eu fiz isso na minha cabeça ...

Maldito garoto. Provavelmente copiou. Eles são todos iguais.

Eu fiz uma descoberta hoje. Eu encontrei um computador. Espere um segundo, isso é legal. Faz o que eu quero. Se cometer um erro, é porque eu estraguei tudo. Não porque não gosta de mim… ou se sente ameaçado por mim… ou pensa que sou um burro esperto… ou não gosta de ensinar e não deveria estar aqui…

Maldito garoto. Tudo o que ele faz é jogar. Eles são todos iguais.
E então aconteceu ... uma porta se abriu para um mundo ... correndo através da linha telefônica como heroína através das veias de um viciado, um pulso eletrônico é enviado, um refúgio das incompetências do dia-a-dia é procurado ... uma placa é encontrada. “Isto é isto… isto é onde eu pertenço…”

Eu conheço todos aqui… mesmo que eu nunca os conheça, nunca falei com eles, talvez nunca mais tenha notícias deles… Eu conheço todos vocês…

Maldito garoto. Amarrando a linha telefônica novamente. Eles são todos iguais ...

Você aposta que somos todos iguais ... temos bebido de papinha na escola quando ansiamos pelo bife ... os pedaços de carne que você deixou escapar foram pré-mastigados e sem gosto. Nós fomos dominados por sádicos ou ignorados pelos apáticos. Os poucos que tinham algo a ensinar nos acharam alunos dispostos, mas esses poucos são como gotas de água no deserto.

Este é o nosso mundo agora ... o mundo do elétron e o interruptor, a beleza do baud. Fazemos uso de um serviço já existente sem pagar pelo que poderia ser barato se não fosse administrado por glutões especuladores, e você nos chama de criminosos. Nós exploramos ... e você nos chama de criminosos. Nós buscamos o conhecimento ... e você nos chama de criminosos. Nós existimos sem cor de pele, sem nacionalidade, sem preconceito religioso ... e você nos chama de criminosos. Você constrói bombas atômicas, faz guerras, mata, engana e mente para nós e tenta nos fazer acreditar que é para nosso próprio bem, mas somos os criminosos.

Sim, sou um criminoso. Meu crime é o da curiosidade. Meu crime é julgar as pessoas pelo que elas dizem e pensam, e não pelo que parecem. Meu crime é o de enganar você, algo que você nunca me perdoará.
Eu sou um hacker e este é o meu manifesto. Você pode parar essa pessoa, mas não pode parar a todos nós ... afinal, somos todos iguais.
.SH AUTHOR 
O Mentor, escrito em 08 de janeiro de 1986

